name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Clear bun cache
        run: bun pm cache clean

      - name: Patch package.json
        run: |
          sed -i 's/"@ozhanefe\/ts-codegenerator": "workspace:*"/"@ozhanefe\/ts-codegenerator": "1.8.0"/' package.json  

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test
