name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Clear Bun cache
        run: |
          bun pm cache clean
          rm -rf node_modules

      - name: Install dependencies
        run: bun install

      - name: Verify ts-codegenerator version
        run: |
          echo "Installed ts-codegenerator version:"
          cat node_modules/@ozhanefe/ts-codegenerator/package.json | grep version
          echo "Is workspace version? (should be empty)"
          find node_modules/@ozhanefe -name "ts-generator" | grep workspace

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test