name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Clear Bun cache and remove node_modules
        run: |
          bun pm cache rm
          rm -rf node_modules

      - name: Install ts-codegenerator from npm
        run: |
          cd apps/next
          bun add @ozhanefe/ts-codegenerator@1.8.0
      - name: Install all dependencies
        run: |
          cd ..
          cd ..
          bun install
          cd $GITHUB_WORKSPACE

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test