name: Release ts-codegenerator

on:
  push:
    branches:
      - main
    paths:
      - "packages/ts-generator/**"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Clear bun cache
        run: bun pm cache clean
        working-directory: ./packages/ts-generator

      - name: Install Dependencies
        run: bun install
        working-directory: ./packages/ts-generator

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          cwd: ./packages/ts-generator
          publish: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
